name: Build and Push Image to Docker
on:
  - push
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: Setup Environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      -
        name: Build NodeJS Project
        run: npm build --if-present
      -
        name: Run NodeJS Project
        run: npm run start
  build_image_and_deploy_to_docker_hub:
    needs: [build_project]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: serhatleventyavas/example1:latest
      -
        name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}